apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-container
          image: kruthim/product-app:latest  
          ports:
            - containerPort: 8200
